version: '3.8'

services:
  server:
    build:
     command: uvicorn main:app --host 0.0.0.0 --port 8000
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server/users.db:/app/users.db
      - ./server:/app
    environment:
      - DB_PATH=/app/users.db

  bot:
    build:
      context: ./Tgb-main

      dockerfile: Dockerfile
    depends_on:
      - server
    volumes:
      - ./bot/favorites.json:/app/favorites.json
      - ./bot/watchlist.json:/app/watchlist.json
      - ./bot/collections.json:/app/collections.json
      - ./bot:/app
    environment:
      - SERVER_URL=http://server:8000
